### ISSUE TITLE
BUG - Edit of Toppeq expense giving error

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#539]
![Screenshot 2020-04-23 at 6 38 32 PM](https://user-images.githubusercontent.com/7425622/80103310-abf60280-8591-11ea-94d6-4d99bed0578f.png)

**Comment by nutank** [comment]
Can still replicate this one @legred21 

Try editing this expense - https://ajency-qa.toppeq.com/cashflow/outflow/planned#/db_73712/edit

**Comment by legred21** [comment]
issue existed in empty notify array. Issue is now fixed by checking notify array for data existence

**Comment by nutank** [comment]
- [ ] Edit of planned expense still gives error. @robiulpro please check the error as shared by @legred21 

```
graphql.execution.InputMapDefinesTooManyFieldsException: The variables input contains a field name '__typename' that is not defined for input object type 'ExpenseRecurrenceInput'
at graphql.execution.ValuesResolver.coerceValueForInputObjectType(ValuesResolver.java:177)
at graphql.execution.ValuesResolver.coerceValue(ValuesResolver.java:162)
at graphql.execution.ValuesResolver.coerceValueForInputObjectType(ValuesResolver.java:183)
at graphql.execution.ValuesResolver.coerceValue(ValuesResolver.java:162)
at graphql.execution.ValuesResolver.getVariableValue(ValuesResolver.java:98)
at graphql.execution.ValuesResolver.coerceArgumentValues(ValuesResolver.java:84)
at graphql.execution.Execution.execute(Execution.java:69)
at graphql.GraphQL.execute(GraphQL.java:546)
editing of planed expense is having invalid attribute in request
```

**Comment by robiulpro** [comment]
@HazelColaco19 
Couldn't replicate on staging. Could you please give me the expense id where you're facing the issue.

**Comment by robiulpro** [comment]
fixed

**Comment by HazelColaco19** [comment]
Tested on Ajency server. Edit was possible for all the fields other than date which is being  tracked in #537 . Can close this issue.


Expense db_95654

**Comment by robiulpro** [comment]
Fixed.

**Comment by HazelColaco19** [comment]
Fixed
