### ISSUE TITLE
BUG - Null pointer exception while syncing deposit data from quickbook

### ISSUE THREAD

**Issue by robiulpro** [ajency/cashflow-issue-tracker#661]
Hibernate: select snstracker0_.id as id1_21_0_, snstracker0_.batch_id as batch_id2_21_0_, snstracker0_.company_id as company_3_21_0_, snstracker0_.consumed_from_sns as consumed4_21_0_, snstracker0_.create_date as create_d5_21_0_, snstracker0_.items_processed as items_pr6_21_0_, snstracker0_.items_published as items_pu7_21_0_, snstracker0_.message as message8_21_0_, snstracker0_.sent_to_elastic as sent_to_9_21_0_, snstracker0_.session_id as session10_21_0_, snstracker0_.status as status11_21_0_, snstracker0_.subject as subject12_21_0_, snstracker0_.topic as topic13_21_0_, snstracker0_.update_date as update_14_21_0_ from sns_tracker snstracker0_ where snstracker0_.id=?
2020-05-13 10:09:09.117  INFO 81236 --- [enerContainer-1] c.t.cashflow.service.OutflowServiceImpl  : DEPOSITS CONSUMED :: 5
2020-05-13 10:09:09.123  INFO 81236 --- [enerContainer-1] c.t.cashflow.service.OutflowServiceImpl  : Deposit obj {"id":"121","syncToken":"0","metaData":{"createdByRef":null,"createTime":1584820856000,"lastModifiedByRef":null,"lastUpdatedTime":1584820856000,"lastChangedInQB":null,"synchronized":null},"customField":[],"attachableRef":[],"domain":"QBO","status":null,"sparse":false,"docNumber":null,"txnDate":1584729000000,"departmentRef":null,"currencyRef":{"value":"USD","name":"United States Dollar","type":null},"exchangeRate":null,"privateNote":null,"txnStatus":null,"linkedTxn":[],"line":[{"id":null,"lineNum":null,"description":null,"amount":226.75,"received":null,"linkedTxn":[{"txnId":"97","txnType":"Payment","txnLineId":"0"}],"detailType":null,"paymentLineDetail":null,"discountLineDetail":null,"taxLineDetail":null,"salesItemLineDetail":null,"descriptionLineDetail":null,"itemBasedExpenseLineDetail":null,"accountBasedExpenseLineDetail":null,"depositLineDetail":null,"purchaseOrderItemLineDetail":null,"salesOrderItemLineDetail":null,"itemReceiptLineDetail":null,"journalEntryLineDetail":null,"groupLineDetail":null,"subTotalLineDetail":null,"customField":[],"lineEx":null,"tdslineDetail":null},{"id":null,"lineNum":null,"description":null,"amount":460.4,"received":null,"linkedTxn":[{"txnId":"94","txnType":"Payment","txnLineId":"0"}],"detailType":null,"paymentLineDetail":null,"discountLineDetail":null,"taxLineDetail":null,"salesItemLineDetail":null,"descriptionLineDetail":null,"itemBasedExpenseLineDetail":null,"accountBasedExpenseLineDetail":null,"depositLineDetail":null,"purchaseOrderItemLineDetail":null,"salesOrderItemLineDetail":null,"itemReceiptLineDetail":null,"journalEntryLineDetail":null,"groupLineDetail":null,"subTotalLineDetail":null,"customField":[],"lineEx":null,"tdslineDetail":null},{"id":null,"lineNum":null,"description":null,"amount":80.0,"received":null,"linkedTxn":[{"txnId":"116","txnType":"Payment","txnLineId":"0"}],"detailType":null,"paymentLineDetail":null,"discountLineDetail":null,"taxLineDetail":null,"salesItemLineDetail":null,"descriptionLineDetail":null,"itemBasedExpenseLineDetail":null,"accountBasedExpenseLineDetail":null,"depositLineDetail":null,"purchaseOrderItemLineDetail":null,"salesOrderItemLineDetail":null,"itemReceiptLineDetail":null,"journalEntryLineDetail":null,"groupLineDetail":null,"subTotalLineDetail":null,"customField":[],"lineEx":null,"tdslineDetail":null},{"id":null,"lineNum":null,"description":null,"amount":81.0,"received":null,"linkedTxn":[{"txnId":"98","txnType":"Payment","txnLineId":"0"}],"detailType":null,"paymentLineDetail":null,"discountLineDetail":null,"taxLineDetail":null,"salesItemLineDetail":null,"descriptionLineDetail":null,"itemBasedExpenseLineDetail":null,"accountBasedExpenseLineDetail":null,"depositLineDetail":null,"purchaseOrderItemLineDetail":null,"salesOrderItemLineDetail":null,"itemReceiptLineDetail":null,"journalEntryLineDetail":null,"groupLineDetail":null,"subTotalLineDetail":null,"customField":[],"lineEx":null,"tdslineDetail":null},{"id":null,"lineNum":null,"description":null,"amount":220.0,"received":null,"linkedTxn":[{"txnId":"101","txnType":"Payment","txnLineId":"0"}],"detailType":null,"paymentLineDetail":null,"discountLineDetail":null,"taxLineDetail":null,"salesItemLineDetail":null,"descriptionLineDetail":null,"itemBasedExpenseLineDetail":null,"accountBasedExpenseLineDetail":null,"depositLineDetail":{"entity":null,"classRef":null,"accountRef":null,"paymentMethodRef":{"value":"2","name":null,"type":null},"checkNum":null,"txnType":null,"taxCodeRef":null,"taxApplicableOn":null,"depositLineDetailEx":null},"purchaseOrderItemLineDetail":null,"salesOrderItemLineDetail":null,"itemReceiptLineDetail":null,"journalEntryLineDetail":null,"groupLineDetail":null,"subTotalLineDetail":null,"customField":[],"lineEx":null,"tdslineDetail":null}],"txnTaxDetail":{"defaultTaxCodeRef":null,"txnTaxCodeRef":null,"totalTax":null,"taxReviewStatus":null,"taxLine":[]},"txnSource":null,"taxFormType":null,"taxFormNum":null,"transactionLocationType":null,"depositToAccountRef":{"value":"35","name":"Checking","type":null},"cashBack":{"accountRef":{"value":"36","name":"Savings","type":null},"amount":200.0,"memo":"Money to savings"},"globalTaxCalculation":null,"totalAmt":868.15,"homeTotalAmt":null,"depositEx":null}
2020-05-13 10:09:09.123  INFO 81236 --- [enerContainer-1] c.t.cashflow.service.OutflowServiceImpl  :  line items cnt 5
2020-05-13 10:09:09.123  INFO 81236 --- [enerContainer-1] c.t.cashflow.service.OutflowServiceImpl  : generatedId qb_deposit_40_121_null
2020-05-13 10:09:09.123  INFO 81236 --- [enerContainer-1] c.t.cashflow.service.OutflowServiceImpl  : qbParentId 121
2020-05-13 10:09:09.177  INFO 81236 --- [enerContainer-1] c.t.cashflow.service.OutflowServiceImpl  : accountingHeadName 
2020-05-13 10:09:09.177  INFO 81236 --- [enerContainer-1] c.t.cashflow.service.OutflowServiceImpl  : currency USD
java.lang.NullPointerException
	at com.toppeq.cashflow.service.OutflowServiceImpl.outFlowFromQuickBookDeposit(OutflowServiceImpl.java:418)
	at com.toppeq.cashflow.service.OutflowServiceImpl.processSNSTopic(OutflowServiceImpl.java:1816)
	at com.toppeq.cashflow.service.SQSConsumerService.processOutflowMessage(SQSConsumerService.java:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:171)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:120)
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:114)
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:77)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:736)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:696)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1189)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1179)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1076)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-05-13 10:09:09.236  INFO 81236 --- [enerContainer-1] c.t.cashflow.service.SQSConsumerService  : Received quickbookData topic
2020-05-13 10:09:09.236  INFO 81236 --- [enerContainer-1] c.t.cashflow.service.OutflowServiceImpl  : RECEIVED TOPIC <> outflow_robiul
Hibernate: select companyset0_.id as id1_7_, companyset0_.company_id as company_2_7_, companyset0_.completion_time as completi3_7_, companyset0_.error as error4_7_, companyset0_.job_type as job_type5_7_, companyset0_.sns_tracker_session_id as sns_trac6_7_, companyset0_.start_time as start_ti7_7_, companyset0_.status as status8_7_, companyset0_.success_ids as success_9_7_ from company_setup_tracker companyset0_ where companyset0_.company_id=? and companyset0_.job_type=? and companyset0_.sns_tracker_session_id=?
Hibernate: select snstracker0_.id as id1_21_, snstracker0_.batch_id as batch_id2_21_, snstracker0_.company_id as company_3_21_, snstracker0_.consumed_from_sns as consumed4_21_, snstracker0_.create_date as create_d5_21_, snstracker0_.items_processed as items_pr6_21_, snstracker0_.items_published as items_pu7_21_, snstracker0_.message as message8_21_, snstracker0_.sent_to_elastic as sent_to_9_21_, snstracker0_.session_id as session10_21_, snstracker0_.status as status11_21_, snstracker0_.subject as subject12_21_, snstracker0_.topic as topic13_21_, snstracker0_.update_date as update_14_21_ from sns_tracker snstracker0_ where snstracker0_.session_id=?
Hibernate: select companyset0_.id as id1_7_, companyset0_.company_id as company_2_7_, companyset0_.completion_time as completi3_7_, companyset0_.error as error4_7_, companyset0_.job_type as job_type5_7_, companyset0_.sns_tracker_session_id as sns_trac6_7_, companyset0_.start_time as start_ti7_7_, companyset0_.status as status8_7_, companyset0_.success_ids as success_9_7_ from company_setup_tracker companyset0_ where companyset0_.company_id=? and companyset0_.job_type=? and companyset0_.sns_tracker_session_id=?
Hibernate: select companyset0_.id as id1_7_0_, companyset0_.company_id as company_2_7_0_, companyset0_.completion_time as completi3_7_0_, companyset0_.error as error4_7_0_, companyset0_.job_type as job_type5_7_0_, companyset0_.sns_tracker_session_id as sns_trac6_7_0_, companyset0_.start_time as start_ti7_7_0_, companyset0_.status as status8_7_0_, companyset0_.success_ids as success_9_7_0_ from company_setup_tracker companyset0_ where companyset0_.id=?
Hibernate: update company_setup_tracker set company_id=?, completion_time=?, error=?, job_type=?, sns_tracker_session_id=?, start_time=?, status=?, success_ids=? where id=?
Hibernate: select nextval ('hibernate_sequence')

**Comment by nutank** [comment]
@legred21 what was the issue here? and what was the fix done?

**Comment by legred21** [comment]
Deposit line item detail type was empty and there was no null check on it. Introduced null check on Deposit line item detail type

**Comment by HazelColaco19** [comment]
Closing the ticket upon discussion with Nutan
