### ISSUE TITLE
BUG - Issues post Company Setup

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#670]
- [x] Quickbook Data page is giving error for company id 1
```
@timestamp:May 14th 2020, 01:19:08.228 tags:multiline, stacktrace, _grokparsefailure type:java host:ip-172-31-0-202 message:2020-05-13 19:49:07,801 WARN graphql.execution.SimpleDataFetcherExceptionHandler [http-nio-8080-exec-7] Exception while fetching data (/getQuickbookData) : null java.lang.NullPointerException: null at com.toppeq.cashflow.service.QuickbookDataServiceImpl.getQuickbookBankData(QuickbookDataServiceImpl.java:143) at com.toppeq.cashflow.service.QuickbookDataServiceImpl.getQuickbookData(QuickbookDataServiceImpl.java:72) at com.toppeq.api.QuickbookDataQuery.getQuickbookData(QuickbookDataQuery.java:25) at com.toppeq.api.QuickbookDataQueryMethodAccess.invoke(Unknown Source) at com.coxautodev.graphql.tools.MethodFieldResolverDataFetcher.get(MethodFieldResolver.kt:132) at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:219) at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:165) at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:55) at graphql.execution.Execution.executeOperation(Execution.java:154) at graphql.execution.Execution.execute(Execution.java:98) at graphql.GraphQL.execute(GraphQL.java:546) at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:488) at graphql.GraphQL.executeAsync(GraphQL.java:463) at graphql.GraphQL.execute(GraphQL.java:394) at graphql.servlet.GraphQLServlet.query(GraphQLServlet.java:338) at graphql.servlet.GraphQLServlet.doQuery(GraphQLServlet.java:300) at graphql.servlet.GraphQLServlet.doQuery(GraphQLServlet.java:296) at graphql.servlet.GraphQLServlet.lambda$new$1(GraphQLServlet.java:196) at graphql.servlet.GraphQLServlet.doRequest(GraphQLServlet.java:254) at graphql.servlet.GraphQLServlet.doPost(GraphQLServlet.java:272) at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:92) at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at com.toppeq.config.ConfigCtrl.doFilter(ConfigCtrl.java:30) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367) at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1591) at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.base/java.lang.Thread.run(Thread.java:834) path:/var/log/toppeq/toppeq.log @version:1 _id:vfSVD3IBhVblZSZQZ1Eu _type:doc _index:toppeq-logstash-2020.05.13 _score:2
```

- [x] None of the charts for company 8 (Flipmo) are loading. Gives following error in logstash. Logstash [link](http://13.234.21.219:5601/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:'2020-05-14T01:57:21.416Z',mode:absolute,to:'2020-05-14T01:58:23.904Z'))&_a=(columns:!(_source),index:b4c02680-78ca-11ea-9bff-17296d6cdc0e,interval:auto,query:(language:lucene,query:''),sort:!(_score,desc)))

```
May 14th 2020, 07:27:32.450 | @version:1 message:2020-05-14 01:56:21,651 ERROR graphql.servlet.DefaultGraphQLErrorHandler [http-nio-8080-exec-5] Error executing query (ExceptionWhileDataFetching): Exception while fetching data (/getDashboardCharts) : null type:java host:ip-172-31-0-202 tags:_grokparsefailure path:/var/log/toppeq/toppeq.log @timestamp:May 14th 2020, 07:27:32.450 _id:HvXmEHIBhVblZSZQrRET _type:doc _index:toppeq-logstash-2020.05.14 _score:2
-- | --

  | May 14th 2020, 07:27:32.455 | @version:1 message:2020-05-14 01:57:32,175 WARN graphql.execution.SimpleDataFetcherExceptionHandler [http-nio-8080-exec-3] Exception while fetching data (/getDashboardCharts) : null java.lang.NullPointerException: null at com.toppeq.api.DashboardQuery.getDashboardCharts(DashboardQuery.java:204) at com.toppeq.api.DashboardQueryMethodAccess.invoke(Unknown Source) at
```

 

- [x] Projection dropdown for "Key Metrics" page is not loading 

- [x] Need dynamic company dropdown selection 

- [x] Flipmo Company 8 (original one) is gone missing in _company_quickbook_accounts_ table. If we try to connect it to Quickbook account with the old url - https://ajency-qa.api.toppeq.com/connectToQuickbooks?companyId=8 , it gives error page first. And does not show up in _company_quickbook_accounts_ table.

![Screenshot 2020-05-14 at 7 37 44 AM](https://user-images.githubusercontent.com/7425622/81884623-f9c0c200-95b5-11ea-999f-33a2ca89ed68.png)

**Comment by nutank** [comment]
URL to use for connecting company using company id is - https://ajency-qa.api.toppeq.com/connectToQuickbooksOld?companyId=8

**Comment by robiulpro** [comment]
@Nutan, i think all are fixed here.

**Comment by HazelColaco19** [comment]
@nutank Just checked " Need dynamic company dropdown selection ", rest were checked before. Closing this issue since it looks all handled.
